python TrainCNO_losses.py shear_layer $1
python TrainCNO_losses.py poisson $1
python TrainCNO_losses.py wave_0_5 $1
python TrainCNO_losses.py allen $1
python TrainCNO_losses.py cont_tran $1
python TrainCNO_losses.py disc_tran $1
python TrainCNO_losses.py airfoil $1
python TrainCNO_losses.py darcy $1
python TrainCNO_losses.py ns $1
